### ISSUE TITLE
trapperkeeper & Nagios

### ISSUE THREAD

**Issue by poblabs** [dropbox/trapperkeeper#14]
Sorry to leave an issue - this is more of a general question. 

How would you propose hooking this into Nagios? 

* Would Nagios be an active check set for every couple of minutes? 
* Can trapperkeeper execute a script when it receives a trap? That way I could send a passive alert to Nagios. 

I'm sort of looking to do something like the 2nd bullet item, but maybe aggressively checking the trapperkeeper API via an active check every 2 minutes isn't a bad idea either?

Thanks

**Comment by gmjosack** [comment]
Internally we have a script hit the API per network device, of which we have a decent number. The TrapperKeeper api works well for this and we haven't had any problems with it.

It's been a while since I've worked on this project. I don't believe we have something directly for number 2 but there's a place you could shim this in, though it's not well documented. 

There's something called the Dynamic Decision Engine which lets you provide a plugin that all traps pass through. This is used to dynamically set things like severity and notification rules based on variables not easily encoded in the config. Since all traps flow through here there's no reason you couldn't inject that logic there:

The interface is to create a module called `trapperkeeper_dde_plugin` which has a `run(dde)` function. The run function takes a dde object as defined https://github.com/dropbox/trapperkeeper/blob/master/trapperkeeper/dde.py#L5

When you run the trapperkeeper binary you just need to make sure the `trapperkeeper_dde_plugin` plugin is available on the `PYTHONPATH`

For the sake of simplicity I'd advise just polling. Specifically you probably don't want to introduce too much IO in DDE as it might block up the actual receipt of traps.

**Comment by poblabs** [comment]
> For the sake of simplicity I'd advise just polling.

I agree, I'll just poll with an active check that Nagios owns. One issue I saw is some traps come in as IP versus hostname so Nagios could complain if that host is defined using hostname (instead of IP). I could probably work my way through that (not an issue for TrapperKeeper). 

Thanks for the great utility. So far it looks to be a lot easier (and hopefully more reliable) than what I'm using now; snmpd, snmptt and snmptrapd.

**Comment by gmjosack** [comment]
No problem! We had the same problems with snmptrapd which is why it was created. Good luck!
